const productos = [{
    nombre: "energética",
    categoria: "vela",
    precio: 120,
    foto: "./img/velaPrendida.jpeg",
    id: 1,
},
{
    nombre: "purificadora",
    categoria: "vela",
    precio: 150,
    foto: "./img/velasPlateadas.jpeg",
    id: 2,
},
{
    nombre: "cuarzo",
    categoria: "piedra",
    precio: 200,
    foto: "./img/piedrasYEstatuilla.jpeg",
    id: 3,
},
{
    nombre: "opalo",
    categoria: "piedra",
    precio: 220,
    foto: "./img/piedrasEnMesa.jpeg",
    id: 4,
},
{
    nombre: "salvia",
    categoria: "hierba",
    precio: 90,
    foto: "./img/rellenoDeSaumerioSolo.jpeg",
    id: 5,
},
{
    nombre: "lavanda",
    categoria: "hierba",
    precio: 120,
    foto: "./img/saumerioConRelleno.jpeg",
    id: 6,
},
]